### ISSUE TITLE
Missing guard

### ISSUE THREAD

**Issue by elcreator** [sebalr/ngx-feature-flags#12]
Documentation says
```
There is also an Route guard

{
    path: 'path-to-feature-a',
    component: FeatureAComponent,
    canActivate: [ FeatureFlagsGuard ],
    data: { featureFlag: 'featureA' }
}
```
but there are no FeatureFlagsGuard in the library API.

import { FeatureFlagsGuard } from 'ngx-feature-flags'; // fails

**Comment by marcelbarner** [comment]
Yes the guard is implemented like you can see in the master, but no new package was released.

**Comment by sebalr** [comment]
I will try to update it.
PR are appreciated

**Comment by marcelbarner** [comment]
PR #13 should solve the problem.

**Comment by marcelbarner** [comment]
PR is closed. With a new version release the issue should be fixed.

**Comment by sebalr** [comment]
version 1.0.1 published. I will try to update Angular version soon
