### ISSUE TITLE
Request: Link testing package

### ISSUE THREAD

**Issue by marcelbarner** [sebalr/ngx-feature-flags#5]
Hello,

we use the package 'ngx-feature-flags' in our project, but we found it a little bit overkill to initialize the package like described for our tests. So I decided to write a package which simplify the using of feature flags in test cases. 
Maybe you can link the package in your README.md so that other users also can use it.

Here is the link to the package:
https://www.npmjs.com/package/ngx-feature-flags-testing

Thanks.

**Comment by sebalr** [comment]
Nice to hear that.
I will definitely add the reference in README.
Would you like to integrate your testing module in this project and became contributor? It's a really good job.

**Comment by sebalr** [comment]
> Hello,
> 
> we use the package 'ngx-feature-flags' in our project, but we found it a little bit overkill to initialize the package like described for our tests. So I decided to write a package which simplify the using of feature flags in test cases.
> Maybe you can link the package in your README.md so that other users also can use it.
> 
> Here is the link to the package:
> https://www.npmjs.com/package/ngx-feature-flags-testing
> 
> Thanks.

Nice to hear that.
I will definitely add the reference in README.
Would you like to integrate your testing module in this project and became contributor? It's a really good job.

**Comment by marcelbarner** [comment]
Hey,

sorry for waiting, I had some vacations.
Yes we can integrate my testing module in yours and i want to become a contributor.
